<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [Gpsd-users] cant get python to talk to gpsd
   </TITLE>
   <LINK REL="Index" HREF="http://lists.berlios.de/pipermail/gpsd-users/2011-March/index.html" >
   <LINK REL="made" HREF="mailto:gpsd-users%40lists.berlios.de?Subject=Re%3A%20%5BGpsd-users%5D%20cant%20get%20python%20to%20talk%20to%20gpsd&In-Reply-To=%3CAANLkTim06-ivUgVWSS-EXu%2B2HpjwHnL6Xq3f-Ustb%3DDo%40mail.gmail.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="005150.html">
   <LINK REL="Next"  HREF="005152.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Gpsd-users] cant get python to talk to gpsd</H1>
    <B>TJ</B> 
    <A HREF="mailto:gpsd-users%40lists.berlios.de?Subject=Re%3A%20%5BGpsd-users%5D%20cant%20get%20python%20to%20talk%20to%20gpsd&In-Reply-To=%3CAANLkTim06-ivUgVWSS-EXu%2B2HpjwHnL6Xq3f-Ustb%3DDo%40mail.gmail.com%3E"
       TITLE="[Gpsd-users] cant get python to talk to gpsd">jordan.trevor at gmail.com
       </A><BR>
    <I>Fri Mar 18 06:16:57 CET 2011</I>
    <P><UL>
        <LI>Previous message: <A HREF="005150.html">[Gpsd-users] cant get python to talk to gpsd
</A></li>
        <LI>Next message: <A HREF="005152.html">[Gpsd-users] cant get python to talk to gpsd
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#5151">[ date ]</a>
              <a href="thread.html#5151">[ thread ]</a>
              <a href="subject.html#5151">[ subject ]</a>
              <a href="author.html#5151">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>&gt;<i>    session = gps()
</I>&gt;<i>
</I>&gt;<i> will use the defaults (local connection), which should work.
</I>&gt;<i>
</I>
it doesn't though. This is what I get when I try that;

&gt;&gt;&gt;<i> import gps
</I>&gt;&gt;&gt;<i> session = gps()
</I>Traceback (most recent call last):
  File &quot;&lt;stdin&gt;&quot;, line 1, in &lt;module&gt;
TypeError: 'module' object is not callable
&gt;&gt;&gt;<i>
</I>

On 18 March 2011 16:57, Thomas Sprinkmeier &lt;<A HREF="https://lists.berlios.de/mailman/listinfo/gpsd-users">thomas.sprinkmeier at gmail.com</A>&gt; wrote:
&gt;&gt;&gt;&gt;&gt;<i> session = gps(**opts)
</I>&gt;&gt;<i> Traceback (most recent call last):
</I>&gt;&gt;<i> &#160;File &quot;&lt;stdin&gt;&quot;, line 1, in &lt;module&gt;
</I>&gt;&gt;<i> NameError: name 'opts' is not defined
</I>&gt;<i>
</I>&gt;<i> &quot;**opts&quot; is a place-holder for options you might like to pass.
</I>&gt;<i>
</I>&gt;<i> &#160; &#160;session = gps()
</I>&gt;<i>
</I>&gt;<i> will use the defaults (local connection), which should work.
</I>&gt;<i>
</I>&gt;<i> Thomas
</I>&gt;<i>
</I>
</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="005150.html">[Gpsd-users] cant get python to talk to gpsd
</A></li>
	<LI>Next message: <A HREF="005152.html">[Gpsd-users] cant get python to talk to gpsd
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#5151">[ date ]</a>
              <a href="thread.html#5151">[ thread ]</a>
              <a href="subject.html#5151">[ subject ]</a>
              <a href="author.html#5151">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.berlios.de/mailman/listinfo/gpsd-users">More information about the Gpsd-users
mailing list</a><br>
</body></html>
